version: '3'
volumes:
  data-postgres:
services:
  #  Node.js
  app:
    build:
      context: ./app
      target: dev
    tty: true
    working_dir: /opt/server
    volumes:
      - ./app:/opt/server
      - ./static:/opt/static
    env_file:
      - .env
    expose:
      - '3000'
    depends_on:
      - postgres

  # Postgres
  postgres:
   container_name: postgres
   image: postgres:13
   restart: always
   volumes:
    - data-postgres:/var/lib/postgresql/data/
   environment:
     - POSTGRES_USER=${DB_USER}
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=postgres
   ports:
     - 5432:5432

  # nginx
  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
      - postgres
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/static
    restart: always

